# Generated by Django 4.2.7 on 2023-12-09 10:06
from django.db import models
from django.contrib.postgres.fields import ArrayField

class UserDesk(models.Model):  # Added (models.Model) to indicate that UserDesk is a model
    username = models.CharField(max_length=128, unique=True)
    hashtoken = models.CharField(max_length=64,blank=True, null=True)

class IPDetails(models.Model):  # Changed IPdetails to IPDetails for PEP 8 compliance
    ipadress = models.CharField(max_length=128,blank=True, null=True)
    name = models.CharField(blank=True, max_length=255, null=True)
    password = models.CharField(max_length=128, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    query_id =models.TextField(blank=True, null=True) 
    user_id = models.ForeignKey(UserDesk, on_delete=models.CASCADE, related_name='ip_books')

class Schedule(models.Model):  # Added (models.Model) to indicate that Schedule is a model
    schedule_name = models.CharField(blank=True, max_length=255, null=True)
    schedule_query_id = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    schedule_date = models.DateTimeField(blank=True, null=True)
    schedule_ipadress = models.ForeignKey(IPDetails, on_delete=models.CASCADE, related_name='schedule_ip_books')
    schedule_user_id = models.ForeignKey(UserDesk, on_delete=models.CASCADE, related_name='schedule_books')
