# Generated by Django 4.1.13 on 2024-01-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awork_public', '0002_comment_user_like_user_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
