# Generated by Django 5.0.1 on 2024-01-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('ipadress', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_id', models.TextField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('desk_sync', models.BooleanField(default=False)),
                ('web_sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('schedule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_query_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('utc', models.CharField(max_length=255, null=True)),
                ('query', models.JSONField()),
                ('schedule_ipadress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_ip_books', to='awork_desktop.ipdetails')),
            ],
        ),
    ]
