# Generated by Django 4.2.7 on 2023-12-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awork_desktop', '0002_ipdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_query_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('schedule_ipadress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_ip_books', to='awork_desktop.ipdetails')),
                ('schedule_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_books', to='awork_desktop.userdesk')),
            ],
        ),
    ]
